version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=sheba_user
      - DB_PASSWORD=sheba_password
      - DB_NAME=sheba_db
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sheba_user
      - POSTGRES_PASSWORD=sheba_password
      - POSTGRES_DB=sheba_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
